services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestionmysoutenance_app
    ports:
      - '${APP_PORT:-8080}:80'
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor # Pour utiliser le vendor de l'image
      - app_uploads:/var/www/html/Public/uploads
      - app_logs:/var/www/html/var/log
    environment:
      - APP_ENV=${APP_ENV:-development}
      - DB_HOST=db
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=root # UTILISATEUR ROOT COMME DEMANDÉ
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD} # UTILISE MYSQL_ROOT_PASSWORD DIRECTEMENT
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - mysoutenance_network

  db:
    image: mysql:8.3
    container_name: gestionmysoutenance_db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password # Pour compatibilité avec certains clients anciens si besoin
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Sera 'root123' via .env
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysoutenance.sql:/docker-entrypoint-initdb.d/mysoutenance.sql
    ports:
      - '${DB_EXTERNAL_PORT:-3306}:3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - mysoutenance_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: gestionmysoutenance_pma
    restart: unless-stopped
    ports:
      - '${PMA_PORT:-8081}:80'
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Utilisé pour la connexion auto
      PMA_USER: root # Connexion automatique avec root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Connexion automatique avec le mot de passe root
      UPLOAD_LIMIT: 128M # Augmenter la limite pour importer des .sql plus gros
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mysoutenance_network

volumes:
  mysql_data:
  app_uploads:
  app_logs:

networks:
  mysoutenance_network:
    driver: bridge