services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: gestionmysoutenance_app_dev
    volumes:
      - ./src:/var/www/html/src
      - ./Public:/var/www/html/Public
      - ./routes:/var/www/html/routes
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/99-custom.ini
      - app_dev_uploads:/var/www/html/Public/uploads
      - app_dev_logs:/var/www/html/var/log
      - app_dev_cache:/var/www/html/var/cache
    env_file:
      - .env.dev
    depends_on:
      db:
        condition: service_healthy
      mailhog:
        condition: service_started
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: gestionmysoutenance_nginx_dev
    ports:
      - "0.0.0.0:8080:80"
    volumes:
      - ./Public:/var/www/html/Public:ro
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: mysql:8.3
    container_name: gestionmysoutenance_db_dev
    restart: unless-stopped
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_dev_data:/var/lib/mysql
      - ./mysoutenance.sql:/docker-entrypoint-initdb.d/mysoutenance.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file:
      - .env.dev
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: gestionmysoutenance_pma_dev
    restart: unless-stopped
    ports:
      - "0.0.0.0:8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 128M
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.dev
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    container_name: gestionmysoutenance_mailhog_dev
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_dev_data:
    driver: local
  app_dev_uploads:
    driver: local
  app_dev_logs:
    driver: local
  app_dev_cache:
    driver: local